"""Executable case matrix for opt-in real model integration tests."""
from __future__ import annotations

from typing import Mapping

from pdebug.otn.tests.infer.model_integration_matrix import (
    MODEL_INTEGRATION_MATRIX,
)
from pdebug.otn.tests.infer.model_integration_support import IntegrationCase


def _by_file() -> Mapping[str, dict]:
    return {item["file"]: item for item in MODEL_INTEGRATION_MATRIX}


def _case(
    *,
    case_id: str,
    file: str,
    node: str,
    description: str,
    args_builder: str,
    requires_cuda: bool = False,
    requires_docker: bool = False,
    required_modules: tuple[str, ...] = (),
    expected_paths: tuple[str, ...] = (),
    repo_url: str | None = None,
    repo_downloads: tuple[tuple[str, str], ...] = (),
) -> IntegrationCase:
    metadata = _by_file()[file]
    return IntegrationCase(
        case_id=case_id,
        file=file,
        node=node,
        description=description,
        args_builder=args_builder,
        official_sources=tuple(metadata["official_sources"]),
        repo_url=repo_url
        if repo_url is not None
        else metadata["repo_url"][0]
        if metadata["repo_url"]
        else None,
        hf_model_ids=tuple(metadata["hf_model_ids"]),
        repo_downloads=repo_downloads,
        preferred_runtime=str(metadata["preferred_runtime"]),
        requires_cuda=requires_cuda,
        requires_docker=requires_docker,
        required_modules=required_modules,
        expected_paths=expected_paths,
        heavy_reason=str(metadata["heavy_reason"]),
    )


MODEL_INTEGRATION_CASES = (
    _case(
        case_id="cotracker",
        file="pdebug/otn/infer/co-tracker.py",
        node="cotracker",
        description="Run CoTracker3 on a tiny generated video.",
        args_builder="video",
        requires_cuda=True,
        required_modules=("torch", "cotracker"),
        expected_paths=("tracked_points.json",),
    ),
    _case(
        case_id="depth_anything_image",
        file="pdebug/otn/infer/depth_anything.py",
        node="depth_anything",
        description="Run Depth Anything image inference.",
        args_builder="depth_anything_image",
        required_modules=("gradio_client",),
    ),
    _case(
        case_id="depth_anything_video",
        file="pdebug/otn/infer/depth_anything.py",
        node="depth-anything-video",
        description="Run Video Depth Anything on a tiny generated video.",
        args_builder="depth_anything_video",
        repo_url=(
            "https://github.com/DepthAnything/Video-Depth-Anything"
        ),
        repo_downloads=(
            (
                "checkpoints/video_depth_anything_vits.pth",
                "https://huggingface.co/depth-anything/"
                "Video-Depth-Anything-Small/resolve/main/"
                "video_depth_anything_vits.pth",
            ),
        ),
        requires_cuda=True,
        required_modules=("torch",),
    ),
    _case(
        case_id="foundpose_templates",
        file="pdebug/otn/infer/foundpose.py",
        node="cad-to-templates",
        description="Render FoundPose-style CAD templates for a cube.",
        args_builder="foundpose_templates",
        required_modules=("trimesh", "pyrender"),
    ),
    _case(
        case_id="genpose2",
        file="pdebug/otn/infer/genpose2.py",
        node="genpose2",
        description="Run GenPose2 on generated RGB-D inputs.",
        args_builder="genpose2",
        requires_cuda=True,
        required_modules=("torch",),
    ),
    _case(
        case_id="groundingdino",
        file="pdebug/otn/infer/groundingdino_node.py",
        node="groundingdino",
        description="Run GroundingDINO detection on one image.",
        args_builder="single_image",
        required_modules=("torch", "transformers"),
    ),
    _case(
        case_id="hunyuan3d_paint",
        file="pdebug/otn/infer/hunyuan3d_paint.py",
        node="hunyuan3d_paint",
        description="Texture a generated cube mesh with Hunyuan3D Paint.",
        args_builder="hunyuan_paint",
        requires_cuda=True,
        required_modules=("torch",),
    ),
    _case(
        case_id="hunyuan3d_rembg",
        file="pdebug/otn/infer/hunyuan3d_rembg.py",
        node="hunyuan3d_rembg",
        description="Run Hunyuan3D background remover on one image.",
        args_builder="hunyuan_rembg",
        required_modules=("torch",),
        expected_paths=("background_removed.json",),
    ),
    _case(
        case_id="hunyuan3d_shape",
        file="pdebug/otn/infer/hunyuan3d_shape.py",
        node="hunyuan3d_shape",
        description="Generate a mesh from one image with Hunyuan3D Shape.",
        args_builder="hunyuan_shape",
        requires_cuda=True,
        required_modules=("torch",),
        expected_paths=("meshes.json",),
    ),
    _case(
        case_id="internimage_semseg",
        file="pdebug/otn/infer/internimage_semseg.py",
        node="internimage_semseg",
        description="Run InternImage/DCNv4 semantic segmentation.",
        args_builder="repo_image_dir",
        requires_cuda=True,
        required_modules=("torch", "mmcv", "mmseg"),
    ),
    _case(
        case_id="langsam_predict",
        file="pdebug/otn/infer/langsam.py",
        node="langsam_predict",
        description="Run LangSAM language-guided segmentation.",
        args_builder="langsam_predict",
        required_modules=("lang_sam", "torch"),
        expected_paths=("metadata", "masks", "vis"),
    ),
    _case(
        case_id="ml_depth_pro",
        file="pdebug/otn/infer/ml_depth_pro_node.py",
        node="ml_depth_pro",
        description="Run Apple's Depth Pro on one image.",
        args_builder="single_image",
        required_modules=("torch", "transformers"),
    ),
    _case(
        case_id="moondream",
        file="pdebug/otn/infer/moondream_node.py",
        node="moondream",
        description="Run Moondream captioning on one image.",
        args_builder="single_image",
        required_modules=("torch", "transformers"),
    ),
    _case(
        case_id="oneposeviagen_3dgen",
        file="pdebug/otn/infer/oneposeviagen_3dgen.py",
        node="oneposeviagen_3dgen",
        description="Run OnePoseViaGen 3D generation.",
        args_builder="oneposeviagen_3dgen",
        requires_cuda=True,
        required_modules=("torch",),
    ),
    _case(
        case_id="oneposeviagen_pose",
        file="pdebug/otn/infer/oneposeviagen_pose.py",
        node="oneposeviagen_pose",
        description="Run OnePoseViaGen/FoundationPose pose estimation.",
        args_builder="oneposeviagen_pose",
        requires_cuda=True,
        required_modules=("torch", "trimesh", "nvdiffrast"),
    ),
    _case(
        case_id="oneposeviagen_scale",
        file="pdebug/otn/infer/oneposeviagen_scale.py",
        node="oneposeviagen_scale",
        description="Run OnePoseViaGen scale recovery.",
        args_builder="oneposeviagen_scale",
        requires_cuda=True,
        required_modules=("trimesh",),
    ),
    _case(
        case_id="orient_anything",
        file="pdebug/otn/infer/orient_anything.py",
        node="orient_anything",
        description="Run Orient Anything orientation estimation.",
        args_builder="repo_image_dir",
        requires_cuda=True,
        required_modules=("torch", "transformers", "huggingface_hub"),
    ),
    _case(
        case_id="qwen2_5_vl",
        file="pdebug/otn/infer/qwen2_5_vl.py",
        node="qwen2_5_vl",
        description="Run Qwen2.5-VL on one image prompt.",
        args_builder="qwen_single_image",
        requires_cuda=True,
        required_modules=("torch", "transformers", "qwen_vl_utils"),
    ),
    _case(
        case_id="sam2",
        file="pdebug/otn/infer/sam2_node.py",
        node="sam2",
        description="Run SAM2 video segmentation on tiny image sequence.",
        args_builder="sam2",
        required_modules=("torch", "sam2"),
    ),
    _case(
        case_id="sam6d",
        file="pdebug/otn/infer/sam6d.py",
        node="sam6d_docker",
        description="Run SAM-6D through the Docker-backed manifest.",
        args_builder="sam6d_docker",
        requires_cuda=True,
        requires_docker=True,
        required_modules=(),
    ),
    _case(
        case_id="segment_anything",
        file="pdebug/otn/infer/segment_anything_node.py",
        node="segment_anything",
        description="Run Segment Anything on one image.",
        args_builder="single_image",
        required_modules=("torch", "transformers"),
    ),
    _case(
        case_id="spatracker",
        file="pdebug/otn/infer/spatracker.py",
        node="spatracker",
        description="Run SpatialTrackerV2 on a tiny generated video.",
        args_builder="repo_video",
        requires_cuda=True,
        required_modules=("torch",),
    ),
    _case(
        case_id="vggt",
        file="pdebug/otn/infer/vggt_node.py",
        node="vggt",
        description="Run VGGT reconstruction on tiny image set.",
        args_builder="image_dir",
        requires_cuda=True,
        required_modules=("torch", "vggt"),
        expected_paths=("extrinsic.npy", "intrinsic.npy", "depth_map.npy"),
    ),
)


def _matrix_case(
    *,
    case_id: str,
    manifest: str,
    sample_data_types: tuple[str, ...],
    args: dict[str, object],
    expected_outputs: tuple[str, ...],
    requirements: tuple[str, ...],
    manual_sample_data: tuple[str, ...] = (),
    notes: tuple[str, ...] = (),
) -> dict[str, object]:
    """Rich case definition reviewed from infer signatures and tests."""
    runner_case = next(
        case for case in MODEL_INTEGRATION_CASES if case.case_id == case_id
    )
    return {
        "case_id": case_id,
        "file": runner_case.file,
        "node": runner_case.node,
        "manifest": manifest,
        "args_builder": runner_case.args_builder,
        "sample_data_types": sample_data_types,
        "args": args,
        "expected_outputs": expected_outputs,
        "requirements": requirements,
        "manual_sample_data": manual_sample_data,
        "notes": notes,
    }


MODEL_INTEGRATION_CASE_MATRIX = (
    _matrix_case(
        case_id="cotracker",
        manifest="pdebug/otn/infer/manifests/cotracker.otn.json",
        sample_data_types=("video",),
        args={
            "input_path": "{fixtures.video}",
            "output": "{output_root}/cotracker",
            "vis_output": "{output_root}/cotracker_vis",
            "max_frames": 3,
            "model_input_size": 3,
            "grid_size": 10,
            "model_name": "cotracker3_offline",
        },
        expected_outputs=(
            "{args.output}/tracked_points.json",
            "{args.vis_output}/*.mp4",
        ),
        requirements=(
            "python:torch",
            "python:cotracker",
            "hardware:cuda",
            "weights:scaled_offline.pth or torch.hub co-tracker",
        ),
    ),
    _matrix_case(
        case_id="depth_anything_image",
        manifest="pdebug/otn/infer/manifests/depth_anything.otn.json",
        sample_data_types=("image",),
        args={
            "image_path": "{fixtures.image}",
            "output": "{output_root}/depth_anything_image.png",
            "do_vis": True,
        },
        expected_outputs=("{args.output}",),
        requirements=(
            "python:gradio_client",
            "network:huggingface_space_depth_anything_api",
        ),
    ),
    _matrix_case(
        case_id="depth_anything_video",
        manifest=(
            "pdebug/otn/infer/manifests/depth_anything_video.otn.json"
        ),
        sample_data_types=("video", "external_repo"),
        args={
            "input_path": "{fixtures.video}",
            "repo": "{repos.Video-Depth-Anything}",
            "output": "{output_root}/depth_anything_video",
            "vis_output": "{output_root}/depth_anything_video_vis",
            "device": "cuda",
            "encoder": "vits",
            "save_npz": True,
            "save_png": False,
            "save_exr": False,
        },
        expected_outputs=(
            "{args.output}/{input_stem}_depths.npz",
            "{args.vis_output}/{input_stem}_src.mp4",
            "{args.vis_output}/{input_stem}_vis.mp4",
        ),
        requirements=(
            "external_repo:Video-Depth-Anything",
            "python:torch",
            "hardware:cuda",
            "weights:video_depth_anything_vits.pth",
        ),
    ),
    _matrix_case(
        case_id="foundpose_templates",
        manifest="pdebug/otn/infer/manifests/cad_to_templates.otn.json",
        sample_data_types=("mesh", "bop_camera"),
        args={
            "model_path": "{fixtures.cube_obj}",
            "output_dir": "{output_root}/foundpose_templates",
            "num_viewspheres": 1,
            "min_num_viewpoints": 4,
            "num_inplane_rotations": 1,
            "topk": 2,
        },
        expected_outputs=(
            "{args.output_dir}/config.json",
            "{args.output_dir}/metadata.json",
            "{args.output_dir}/rgb/template_0000.png",
            "{args.output_dir}/depth/template_0000.png",
            "{args.output_dir}/mask/template_0000.png",
        ),
        requirements=(
            "python:pyrender",
            "python:trimesh",
            "env:BOP_DATASET_PATH containing lmo/camera.json",
        ),
        manual_sample_data=("bop_camera",),
    ),
    _matrix_case(
        case_id="genpose2",
        manifest="pdebug/otn/infer/manifests/genpose2.otn.json",
        sample_data_types=(
            "rgb_imgdir",
            "depth_imgdir",
            "mask_imgdir",
            "genpose2_meta",
            "external_repo",
        ),
        args={
            "rgb_path": "{fixtures.image_dir}",
            "depth_path": "{fixtures.depth_dir}",
            "mask_path": "{fixtures.mask_dir}",
            "meta_path": "{fixtures.genpose2_meta}",
            "repo": "{repos.GenPose2}",
            "output": "{output_root}/genpose2",
            "topk": 1,
            "tracking_by_icp": False,
        },
        expected_outputs=("{args.output}/{first_frame_stem}_pose.json",),
        requirements=(
            "external_repo:GenPose2",
            "python:torch",
            "hardware:cuda",
            "weights:ScoreNet/scorenet.pth",
            "weights:EnergyNet/energynet.pth",
            "weights:ScaleNet/scalenet.pth",
        ),
        manual_sample_data=("genpose2_meta",),
    ),
    _matrix_case(
        case_id="groundingdino",
        manifest="pdebug/otn/infer/manifests/groundingdino.otn.json",
        sample_data_types=("image",),
        args={
            "input_path": "{fixtures.image}",
            "output": "{output_root}/groundingdino.json",
        },
        expected_outputs=("{args.output}",),
        requirements=(
            "python:torch",
            "python:transformers",
            "weights:huggingface:IDEA-Research/grounding-dino-base",
        ),
    ),
    _matrix_case(
        case_id="hunyuan3d_paint",
        manifest="pdebug/otn/infer/manifests/hunyuan3d_paint.otn.json",
        sample_data_types=("mesh", "image", "external_repo"),
        args={
            "repo": "{repos.hunyuan3d-2.1}",
            "mesh_path": "{fixtures.cube_obj}",
            "image_path": "{fixtures.image}",
            "output": "{output_root}/hunyuan3d_paint",
            "face_count": 1000,
            "cache": False,
        },
        expected_outputs=(
            "{args.output}/textures.json",
            "{args.output}/{mesh_stem}_textured.glb",
        ),
        requirements=(
            "external_repo:Hunyuan3D-2.1",
            "python:torch",
            "python:diffusers",
            "python:transformers",
            "python:trimesh",
            "weights:huggingface:tencent/Hunyuan3D-2.1",
        ),
    ),
    _matrix_case(
        case_id="hunyuan3d_rembg",
        manifest="pdebug/otn/infer/manifests/hunyuan3d_rembg.otn.json",
        sample_data_types=("image", "external_repo"),
        args={
            "repo": "{repos.hunyuan3d-2.1}",
            "input_path": "{fixtures.image}",
            "output": "{output_root}/hunyuan3d_rembg",
            "output_format": "RGBA",
            "cache": False,
        },
        expected_outputs=(
            "{args.output}/background_removed.json",
            "{args.output}/{image_stem}_no_bg.png",
        ),
        requirements=(
            "external_repo:Hunyuan3D-2.1",
            "python:torch",
            "python:torchvision",
            "weights:Hunyuan3D background remover",
        ),
    ),
    _matrix_case(
        case_id="hunyuan3d_shape",
        manifest="pdebug/otn/infer/manifests/hunyuan3d_shape.otn.json",
        sample_data_types=("rgba_image", "external_repo"),
        args={
            "repo": "{repos.hunyuan3d-2.1}",
            "input_path": "{fixtures.image}",
            "output": "{output_root}/hunyuan3d_shape",
            "octree_resolution": 64,
            "num_inference_steps": 1,
            "num_chunks": 1000,
            "cache": False,
        },
        expected_outputs=(
            "{args.output}/meshes.json",
            "{args.output}/{image_stem}_shape.glb",
        ),
        requirements=(
            "external_repo:Hunyuan3D-2.1",
            "python:torch",
            "python:diffusers",
            "python:transformers",
            "weights:huggingface:tencent/Hunyuan3D-2.1",
        ),
    ),
    _matrix_case(
        case_id="internimage_semseg",
        manifest="pdebug/otn/infer/manifests/internimage_semseg.otn.json",
        sample_data_types=("imgdir",),
        args={
            "input_path": "{fixtures.image_dir}",
            "output": "{output_root}/internimage_semseg",
            "vis_output": "{output_root}/internimage_semseg_vis",
            "topk": 1,
            "device": "cuda:0",
            "model_type": "small",
            "cache": False,
        },
        expected_outputs=(
            "{args.output}/{first_image_name}",
            "{args.vis_output}/{first_image_name}",
        ),
        requirements=(
            "external_repo:DCNv4",
            "python:torch",
            "python:mmcv",
            "python:mmseg",
            "hardware:cuda",
            "weights:huggingface:OpenGVLab/DCNv4",
        ),
    ),
    _matrix_case(
        case_id="langsam_predict",
        manifest="pdebug/otn/infer/manifests/langsam_predict.otn.json",
        sample_data_types=("imgdir", "text_prompt"),
        args={
            "input_path": "{fixtures.image_dir}",
            "texts": "red square",
            "output": "{output_root}/langsam_predict",
            "sam_type": "sam2.1_hiera_tiny",
            "device": "cuda",
            "box_threshold": 0.15,
            "text_threshold": 0.15,
            "topk": 1,
            "cache": False,
        },
        expected_outputs=(
            "{args.output}/masks/*.png",
            "{args.output}/vis/*.jpg",
            "{args.output}/metadata/*.json",
        ),
        requirements=(
            "python:lang_sam",
            "python:torch",
            "weights:GroundingDINO/SAM via lang-sam",
        ),
    ),
    _matrix_case(
        case_id="ml_depth_pro",
        manifest="pdebug/otn/infer/manifests/ml_depth_pro.otn.json",
        sample_data_types=("image",),
        args={
            "input_path": "{fixtures.image}",
            "output": "{output_root}/ml_depth_pro.json",
        },
        expected_outputs=("{args.output}",),
        requirements=(
            "python:torch",
            "python:transformers",
            "weights:huggingface:apple/DepthPro-hf",
        ),
    ),
    _matrix_case(
        case_id="moondream",
        manifest="pdebug/otn/infer/manifests/moondream.otn.json",
        sample_data_types=("image",),
        args={
            "input_path": "{fixtures.image}",
            "output": "{output_root}/moondream.json",
        },
        expected_outputs=("{args.output}",),
        requirements=(
            "python:torch>=2.5",
            "python:transformers",
            "weights:huggingface:vikhyatk/moondream2@2025-06-21",
            "model_option:trust_remote_code",
        ),
    ),
    _matrix_case(
        case_id="oneposeviagen_3dgen",
        manifest="pdebug/otn/infer/manifests/oneposeviagen_3dgen.otn.json",
        sample_data_types=("rgb_imgdir", "mask_imgdir", "external_repo"),
        args={
            "rgb_path": "{fixtures.image_dir}",
            "masks_path": "{fixtures.mask_dir}",
            "repo": "{repos.OnePoseviaGen}",
            "output": "{output_root}/oneposeviagen_3dgen",
            "randomize_seed": False,
            "ss_sampling_steps": 1,
            "slat_sampling_steps": 1,
            "model_type": "hi3dgen",
        },
        expected_outputs=(
            "{args.output}/final_mask.png",
            "{args.output}/model/model.obj",
            "{args.output}/model/high_mesh.obj",
            "{args.output}/model/preview.mp4",
            "{args.output}/metadata.json",
        ),
        requirements=(
            "external_repo:OnePoseviaGen",
            "python:torch",
            "hardware:cuda",
            "weights:OnePoseViaGen/Hi3DGen_Color",
        ),
    ),
    _matrix_case(
        case_id="oneposeviagen_pose",
        manifest="pdebug/otn/infer/manifests/oneposeviagen_pose.otn.json",
        sample_data_types=(
            "rgb_imgdir",
            "depth_imgdir",
            "mask_imgdir",
            "mesh",
            "camera",
            "external_repo",
        ),
        args={
            "rgb_path": "{fixtures.image_dir}",
            "depth_path": "{fixtures.depth_dir}",
            "masks_path": "{fixtures.mask_dir}",
            "model_path": "{fixtures.cube_obj}",
            "repo": "{repos.OnePoseviaGen}",
            "intrinsics_path": "{fixtures.intrinsics_json}",
            "output": "{output_root}/oneposeviagen_pose",
            "est_refine_iter": 1,
            "track_refine_iter": 1,
        },
        expected_outputs=(
            "{args.output}/poses.json",
            "{args.output}/pose_video.mp4",
            "{args.output}/pose_viz/pose_000000.jpg",
        ),
        requirements=(
            "external_repo:OnePoseviaGen/FoundationPose",
            "python:torch",
            "python:nvdiffrast",
            "python:trimesh",
            "hardware:cuda",
            "weights:FoundationPose score/refine checkpoints",
        ),
    ),
    _matrix_case(
        case_id="oneposeviagen_scale",
        manifest="pdebug/otn/infer/manifests/oneposeviagen_scale.otn.json",
        sample_data_types=(
            "rgb_imgdir",
            "depth_imgdir",
            "mask_imgdir",
            "mesh",
            "camera",
            "external_repo",
        ),
        args={
            "model_path": "{fixtures.cube_obj}",
            "depth_path": "{fixtures.depth_dir}",
            "rgb_path": "{fixtures.image_dir}",
            "masks_path": "{fixtures.mask_dir}",
            "repo": "{repos.OnePoseviaGen}",
            "intrinsics_path": "{fixtures.intrinsics_json}",
            "output": "{output_root}/oneposeviagen_scale",
            "refine_iterations": 1,
        },
        expected_outputs=(
            "{args.output}/scaled_model.obj",
            "{args.output}/high_scaled_model.obj",
            "{args.output}/scale_info.json",
            "{args.output}/temp/intrinsic.txt",
        ),
        requirements=(
            "external_repo:OnePoseviaGen",
            "python:trimesh",
            "module:fpose.recover_scale",
            "hardware:cuda",
        ),
    ),
    _matrix_case(
        case_id="orient_anything",
        manifest="pdebug/otn/infer/manifests/orient_anything.otn.json",
        sample_data_types=("imgdir", "external_repo"),
        args={
            "input_path": "{fixtures.image_dir}",
            "repo": "{repos.Orient-Anything}",
            "output": "{output_root}/orient_anything",
            "vis_output": "{output_root}/orient_anything_vis",
            "topk": 1,
            "device": "cuda:0",
            "cache": False,
        },
        expected_outputs=("{args.vis_output}/visualization.mp4",),
        requirements=(
            "external_repo:Orient-Anything",
            "python:torch",
            "python:transformers",
            "python:huggingface_hub",
            "hardware:cuda",
            "weights:huggingface:Viglong/Orient-Anything",
        ),
    ),
    _matrix_case(
        case_id="qwen2_5_vl",
        manifest="pdebug/otn/infer/manifests/qwen2_5_vl.otn.json",
        sample_data_types=("imgdir", "text_prompt"),
        args={
            "input_path": "{fixtures.image_dir}",
            "text": "List the visible objects in this image.",
            "output": "{output_root}/qwen2_5_vl.txt",
            "cache": False,
        },
        expected_outputs=("{args.output}",),
        requirements=(
            "python:torch",
            "python:transformers",
            "python:qwen_vl_utils",
            "weights:huggingface:Qwen/Qwen2.5-VL-7B-Instruct",
        ),
        notes=(
            "Real qwen2_5_vl.main treats file paths as video input; use an "
            "image directory for the minimal real image case.",
        ),
    ),
    _matrix_case(
        case_id="sam2",
        manifest="pdebug/otn/infer/manifests/sam2.otn.json",
        sample_data_types=("imgdir", "points_json"),
        args={
            "input_path": "{fixtures.image_dir}",
            "points": "{fixtures.sam2_points_json}",
            "output": "{output_root}/sam2",
            "vis_output": "{output_root}/sam2_vis",
            "checkpoint": "tiny",
            "device": "cuda",
            "cache": False,
        },
        expected_outputs=(
            "{args.output}/{first_frame_stem}.png",
            "{args.vis_output}/visualization.mp4",
        ),
        requirements=(
            "python:sam2",
            "python:torch",
            "weights:SAM2.1 checkpoint or Hugging Face access",
        ),
    ),
    _matrix_case(
        case_id="sam6d",
        manifest="pdebug/otn/infer/manifests/sam6d.otn.json",
        sample_data_types=("rgb_imgdir", "depth_imgdir", "mesh", "camera"),
        args={
            "rgb_path": "{fixtures.image_dir}",
            "depth_path": "{fixtures.depth_dir}",
            "cad_path": "{fixtures.cube_obj}",
            "camera_path": "{fixtures.camera_json}",
            "repo": "{repos.SAM-6D}",
            "output": "{output_root}/sam6d",
            "skip_pose": True,
            "seg_first_frame": True,
            "cache": False,
        },
        expected_outputs=(
            "{args.output}/templates",
            "{args.output}/{first_frame_stem}/sam6d_results/"
            "detection_ism.json",
        ),
        requirements=(
            "external_repo:SAM-6D",
            "python:torch",
            "python:pycocotools",
            "tool:blenderproc",
            "hardware:cuda",
            "weights:SAM-6D segmentation/checkpoints",
            "docker:SAM-6D docker manifest available",
        ),
    ),
    _matrix_case(
        case_id="segment_anything",
        manifest="pdebug/otn/infer/manifests/segment_anything.otn.json",
        sample_data_types=("image",),
        args={
            "input_path": "{fixtures.image}",
            "output": "{output_root}/segment_anything.json",
        },
        expected_outputs=("{args.output}",),
        requirements=(
            "python:torch",
            "python:transformers",
            "weights:huggingface:facebook/sam-vit-base",
        ),
    ),
    _matrix_case(
        case_id="spatracker",
        manifest="pdebug/otn/infer/manifests/spatracker.otn.json",
        sample_data_types=("video", "external_repo"),
        args={
            "input_path": "{fixtures.video}",
            "repo": "{repos.SpaTrackerV2}",
            "output": "{output_root}/spatracker",
            "vis_output": "{output_root}/spatracker_vis",
            "max_frames": 3,
            "model_input_size": 3,
            "topk": 3,
            "cache": False,
        },
        expected_outputs=(
            "{args.output}/depth/000000.png",
            "{args.output}/intrinsic/000000.json",
            "{args.vis_output}/depth_000.mp4",
        ),
        requirements=(
            "external_repo:SpaTrackerV2",
            "python:torch",
            "hardware:cuda",
            "weights:huggingface:Yuxihenry/SpatialTrackerV2_Front",
            "weights:huggingface:Yuxihenry/SpatialTrackerV2-Offline",
        ),
    ),
    _matrix_case(
        case_id="vggt",
        manifest="pdebug/otn/infer/manifests/vggt.otn.json",
        sample_data_types=("imgdir",),
        args={
            "input_path": "{fixtures.image_dir}",
            "output": "{output_root}/vggt",
            "max_image_num": 3,
            "sample_mode": "topk",
            "use_ba": False,
            "save_colmap": False,
            "cache": False,
        },
        expected_outputs=(
            "{args.output}/extrinsic.npy",
            "{args.output}/intrinsic.npy",
            "{args.output}/depth_map.npy",
            "{args.output}/depth_conf.npy",
            "{args.output}/points_3d.npy",
            "{args.output}/imglist.txt",
        ),
        requirements=(
            "python:torch",
            "python:vggt",
            "hardware:cuda recommended",
            "weights:huggingface:facebook/VGGT-1B",
        ),
    ),
)


CASE_MATRIX_BY_ID = {
    str(case["case_id"]): case for case in MODEL_INTEGRATION_CASE_MATRIX
}

CASE_IDS_REQUIRING_MANUAL_SAMPLE_DATA = tuple(
    str(case["case_id"])
    for case in MODEL_INTEGRATION_CASE_MATRIX
    if case["manual_sample_data"]
)
