#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
import argparse
import os, sys
import cv2
import numpy as np
from termcolor import cprint
import tqdm
from collections import OrderedDict as odict


class Concat:
    """
    Concat images.
    """
    def __init__(self, length, titles=None, vertical=False, horizontal=False, fisheye=False, title_pos='lr'):
        self.length = length
        self.titles = titles
        self.title_pos = title_pos
        assert title_pos in ('tl', 'bl', 'tr', 'br')
        if titles:
            assert len(titles) == length
        self.concat_axis = None
        if vertical:
            self.concat_axis = 0
        if horizontal:
            self.concat_axis = 1

        if fisheye:
            assert length == 4 or length == 5
            self.concat_fn = eval('self.concat_fisheye')
        else:
            try:
                self.concat_fn = eval('self.concat_%d' % length)
            except Exception as e:
                cprint('imgdir len %d NotImplementedError' % length, 'red')
                sys.exit()

    def __call__(self, *x):
        imgs = list()
        for ind, imgfile in enumerate(x):
            img = cv2.imread(imgfile)
            if self.titles:
                title = self.titles[ind]
                if self.title_pos == 'tl':
                    text_pos = (50, 100)
                elif self.title_pos == 'bl':
                    text_pos = (50, img.shape[0] - 100)
                elif self.title_pos == 'tr':
                    text_pos = (img.shape[1] - 50, 100)
                elif self.title_pos == 'br':
                    text_pos = (img.shape[1] - 50, img.shape[0] - 100)
                else:
                    raise ValueError

                img = cv2.putText(img, title,text_pos, cv2.FONT_HERSHEY_COMPLEX, 1, (0,0,255), 2)
            imgs.append(img)
        return self.concat_fn(*imgs)

    def concat_2(self, *x, axis=1):
        assert len(x) == 2
        if self.concat_axis is not None:
            axis = self.concat_axis
        return np.concatenate((x[0], x[1]), axis=axis)

    def concat_3(self, *x, axis=1):
        assert len(x) == 3
        if self.concat_axis is not None:
            return np.concatenate(x, axis=self.concat_axis)
        return np.concatenate((x[0], x[1], x[2]), axis=axis)
        # bg = np.zeros_like(x[0])
        # x = list(x)
        # x.append(bg)
        # return self.concat_4(*x)

    def concat_4(self, *x):
        assert len(x) == 4
        if self.concat_axis is not None:
            return np.concatenate(x, axis=self.concat_axis)
        row1 = self.concat_2(*x[0:2], axis=1) 
        row2 = self.concat_2(*x[2:4], axis=1) 
        return self.concat_2(row1, row2, axis=0)

    def concat_6(self, *x):
        assert len(x) == 6
        if self.concat_axis is not None:
            return np.concatenate(x, axis=self.concat_axis)
        row1 = np.concatenate(x[:2], axis=1)
        row2 = np.concatenate(x[2:4], axis=1)
        row3 = np.concatenate(x[4:], axis=1)
        return np.concatenate((row1, row2, row3), axis=0)

    def concat_7(self, *x):
        assert len(x) == 7
        if self.concat_axis is not None:
            axis = self.concat_axis
            return np.concatenate(x, axis=axis)
        bg = np.zeros_like(x[0])
        x = list(x)
        x.append(bg)
        return self.concat_8(*x)

    def concat_8(self, *x):
        assert len(x) == 8
        if self.concat_axis is not None:
            return np.concatenate(x, axis=self.concat_axis)
        row1 = np.concatenate(x[:4], axis=1)
        row2 = np.concatenate(x[4:], axis=1)
        return np.concatenate((row1, row2), axis=0)

    def concat_9(self, *x):
        assert len(x) == 9
        if self.concat_axis is not None:
            return np.concatenate(x, axis=self.concat_axis)
        row1 = self.concat_3(*x[0:3], axis=1) 
        row2 = self.concat_3(*x[3:6], axis=1) 
        row3 = self.concat_3(*x[6:9], axis=1) 
        return self.concat_3(row1, row2, row3, axis=0)

    def concat_fisheye(self, *x):
        bg = np.zeros_like(x[0])
        if self.length == 4:
            all_x = [bg, x[0], bg,
                     x[1], bg, x[2],
                     bg, x[3], bg]
        elif self.length == 5:
            # a bit hard code
            if x[2].shape != x[0].shape:
                padding_x2 = bg.copy()
                start_x = (bg.shape[1] - x[2].shape[1]) // 2
                end_x = start_x + x[2].shape[1]
                padding_x2[:, start_x:end_x] = x[2]
            else:
                padding_x2 = x[2]
            all_x = [bg, x[0], bg,
                     x[1], padding_x2, x[3],
                     bg, x[4], bg]
        return self.concat_9(*all_x)

def main(args):
    if args.output is None:
        args.output = 'result_concat'
    if not os.path.exists(args.output):
        os.makedirs(args.output)

    if ',' in args.imgdirs:
        split_flag = ','
    elif ':' in args.imgdirs:
        split_flag = ':'
    else:
        cprint('Please use , or : to split multi imgdirs.', 'red')
        sys.exit()

    imgdirs = [x for x in args.imgdirs.split(split_flag) if x.strip() != '']
    titles = None
    if args.titles:
        titles = args.titles.split(split_flag)
        if args.titles == "None":
            titles = None
    else:
        titles = args.imgdirs.split(split_flag)
    num_imgdir = len(imgdirs)
    cprint("imgdir num: %d" % num_imgdir, 'green') 

    all_imgfiles = []
    all_imglength = []
    for imgdir in imgdirs:
        imgfiles = sorted([os.path.join(imgdir, x) for x in sorted(os.listdir(imgdir)) if x.endswith(args.ext)])
        if len(imgfiles) == 0:
            imgfiles = sorted([os.path.join(imgdir, x) for x in sorted(os.listdir(imgdir))])
        imgfiles = odict({os.path.basename(x): x for x in imgfiles})
        all_imgfiles.append(imgfiles)
        all_imglength.append(len(imgfiles))
    
    min_idx = np.argmin(all_imglength)
    cur_imgfiles = all_imgfiles[min_idx]
    if num_imgdir * len(cur_imgfiles) != np.sum(all_imglength):
        cprint("found different imgdir length, use min length imgdir", 'red') 

    if args.clean:
        cprint("clean image names ...", "green")
        img_names_cnt = {}
        for imgfiles in all_imgfiles:
            for imgname in imgfiles:
                if imgname in img_names_cnt:
                    img_names_cnt[imgname] += 1
                else:
                    img_names_cnt[imgname] = 1
        img_names = [k for k in img_names_cnt if img_names_cnt[k] == len(all_imgfiles)]

    elif args.proportion:
        assert args.by_order, "--proportion should be used together with --by-order"
        propor_list = [i // min(all_imglength) for i in all_imglength]
        for ind, imgfiles in enumerate(all_imgfiles):
            propor = propor_list[ind]
            select_imgnames = list(imgfiles.keys())[0::propor]
            all_imgfiles[ind] = odict({key: imgfiles[key] for key in select_imgnames}) 
            cprint(f"downsample: {len(imgfiles)} => {len(all_imgfiles[ind])}", "green")
        img_names = list(cur_imgfiles.keys())
    else:
        img_names = list(cur_imgfiles.keys())

    concat = Concat(
        num_imgdir,
        titles=titles,
        title_pos=args.title_pos,
        vertical=args.vertical,
        horizontal=args.horizontal,
        fisheye=args.fisheye,
    )
        
    t = tqdm.tqdm(total=len(img_names))
    for ind, key in enumerate(img_names):
        t.update()
        imgfile_list = list()
        for imgfiles in all_imgfiles:
            if args.by_order:
                imgfile_list.append(list(imgfiles.values())[ind])
            else:    
                imgfile_list.append(imgfiles[key])
        img_concat = concat(*imgfile_list)
        cv2.imwrite(os.path.join(args.output, os.path.basename(imgfile_list[0])), img_concat)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Concat two image from two ')
    parser.add_argument('--imgdirs', default=None, type=str, help='input imgdirs', required=True)
    parser.add_argument('--titles', default=None, type=str, help='image title')
    parser.add_argument('--title-pos', dest='title_pos', default='tl', type=str, help='title position')
    parser.add_argument('--ext', default='.jpg', type=str, help='image ext')
    parser.add_argument('--vertical', dest='vertical', action='store_true', help='concat in vertical')
    parser.add_argument('--horizontal', dest='horizontal', action='store_true', help='concat in horizontal')
    parser.add_argument('--fisheye', dest='fisheye', action='store_true', help='description')

    parser.add_argument('--clean', dest='clean', action='store_true', help='clean image names')
    parser.add_argument('--proportion', dest='proportion', action='store_true', help='description')
    parser.add_argument('--by-order', dest='by_order', action='store_true', help='description')

    parser.add_argument('--output', default=None, type=str, help='output')
    args = parser.parse_args()
    main(args)
