#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
import argparse
import os, sys
import cv2
from termcolor import cprint
import tqdm
from wyy import mp


def main(args):
    if args.output is None:
        args.output = 'result_resized'
    if not os.path.exists(args.output):
        os.makedirs(args.output)

    exts = ('.jpg', '.png', '.jpeg', '.JPG', '.PNG', '.JPEG')
    imgfiles = sorted([os.path.join(args.imgdir, x) for x in sorted(os.listdir(args.imgdir))
                       if os.path.splitext(x)[1] in exts])

    @mp(nums=4)
    def _process(imgfiles):
        t = tqdm.tqdm(total=len(imgfiles))
        for imgfile in imgfiles:
            t.update()
            img = cv2.imread(imgfile)
            dst_h = int(img.shape[0] * args.factor)
            dst_w = int(img.shape[1] * args.factor)
            img = cv2.resize(img, (dst_w, dst_h))
            savename = os.path.join(args.output, os.path.basename(imgfile))
            cv2.imwrite(savename, img)

    _process(imgfiles)
    cprint(f'saved in {args.output}', 'green')


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Resize imgdir')
    parser.add_argument('--imgdir', default=None, type=str, help='input imgdirs', required=True)
    parser.add_argument('--factor', type=float, help='resize factor', required=True)
    parser.add_argument('--output', default=None, type=str, help='output')
    args = parser.parse_args()
    main(args)
